# Generated by Django 4.2.3 on 2023-08-13 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Print',
            new_name='Price',
        ),
    ]
