# Generated by Django 4.2.5 on 2023-09-10 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_rename_date_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Total',
            field=models.IntegerField(default=0),
        ),
    ]
