# Generated by Django 4.2.5 on 2023-09-15 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_alter_order_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Total',
            field=models.IntegerField(),
        ),
    ]
